// Structure remains the same as your previous version
import { Mic, BarChart3, Target, LineChart } from "lucide-react";
import "./features.scss";
import SectionEyebrow from "../SectionEyebrow/SectionEyebrow";
import SectionHeadline from "../SectionHeadline/SectionHeadline";
import SectionSubHeadline from "../SectionSubHeadline/SectionSubHeadline";

const features = [
  {
    title: "AI Mock Interviews",
    desc: "Engage in lifelike simulations with adaptive questions generated by our core AI engine.",
    icon: <Mic size={28} />,
  },
  {
    title: "Structured Feedback",
    desc: "Receive comprehensive reports on your tone, technical accuracy, and body language.",
    icon: <BarChart3 size={28} />,
  },
  {
    title: "Skill Gap Analysis",
    desc: "Identify the exact missing pieces in your knowledge compared to industry benchmarks.",
    icon: <Target size={28} />,
  },
  {
    title: "Progress Tracking",
    desc: "Visualize your growth over time with interactive charts and historical performance data.",
    icon: <LineChart size={28} />,
  }
];

const Features = () => {
  return (
    <section className="features-section">
      <div className="features-container">
        <div className="features-header">
          <SectionEyebrow text="Core Capabilities" />
          <SectionHeadline text="Everything you need to" gradient_text="succeed." />
          <SectionSubHeadline text="HirePilot combines advanced AI with proven coaching methods to turn your weaknesses into your greatest strengths." />
        </div>

        <div className="feature-grid">
          {features.map((feature, index) => (
            <div key={index} className="feature-card">
              <div className="card-border-gradient"></div>
              <div className="feature-card-inner">
                <div className="feature-icon-box">
                  {feature.icon}
                </div>
                <h3>{feature.title}</h3>
                <p>{feature.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;