import { Mic, BarChart3, Target, LineChart } from "lucide-react";
import FeatureCard from "./FeatureCard/FeatureCard";
import VisualHeader from "../../VisualHeader/VisualHeader";
import { Box, Container, Grid } from '@mui/material';

const features = [
  {
    title: "AI Mock Interviews",
    desc: "Engage in lifelike simulations with adaptive questions generated by our core AI engine.",
    icon: <Mic size={28} />,
  },
  {
    title: "Structured Feedback",
    desc: "Receive comprehensive reports on your tone, technical accuracy, and body language.",
    icon: <BarChart3 size={28} />,
  },
  {
    title: "Skill Gap Analysis",
    desc: "Identify the exact missing pieces in your knowledge compared to industry benchmarks.",
    icon: <Target size={28} />,
  },
  {
    title: "Progress Tracking",
    desc: "Visualize your growth over time with interactive charts and historical performance data.",
    icon: <LineChart size={28} />,
  }
];

const Features = () => {
  return (
    <Box component="section" sx={{ py: { xs: 8, md: 4 }, position: 'relative', overflow: 'hidden' }}>
      <Container maxWidth="lg" sx={{ position: 'relative', zIndex: 1 }}>
        <Box sx={{ mb: 8, textAlign: 'center' }}>
          <VisualHeader
            badge="Core Capabilities"
            title="Everything you need to"
            gradient_title="succeed."
            subtitle="HirePilot combines advanced AI with proven coaching methods to turn your weaknesses into your greatest strengths."
          />
        </Box>

        <Grid container spacing={2}>
          {features.map((feature, index) => (
            <Grid size={{ xs: 12, md: 6, lg: 3 }} key={index}>
              <FeatureCard {...feature} />
            </Grid>
          ))}
        </Grid>
      </Container>
    </Box>
  );
};

export default Features;