// Structure remains the same as your previous version
import { Mic, BarChart3, Target, LineChart } from "lucide-react";
import "./features.scss";
import FeatureCard from "./FeatureCard/FeatureCard";
import VisualHeader from "../../VisualHeader/VisualHeader";

const features = [
  {
    title: "AI Mock Interviews",
    desc: "Engage in lifelike simulations with adaptive questions generated by our core AI engine.",
    icon: <Mic size={28} />,
  },
  {
    title: "Structured Feedback",
    desc: "Receive comprehensive reports on your tone, technical accuracy, and body language.",
    icon: <BarChart3 size={28} />,
  },
  {
    title: "Skill Gap Analysis",
    desc: "Identify the exact missing pieces in your knowledge compared to industry benchmarks.",
    icon: <Target size={28} />,
  },
  {
    title: "Progress Tracking",
    desc: "Visualize your growth over time with interactive charts and historical performance data.",
    icon: <LineChart size={28} />,
  }
];

const Features = () => {
  return (
    <section className="features-section">
      <div className="features-container">
        <div className="features-header">
          <VisualHeader badge="Core Capabilities" title="Everything you need to" gradient_title="succeed." subtitle="HirePilot combines advanced AI with proven coaching methods to turn your weaknesses into your greatest strengths." />
        </div>

        <div className="feature-grid">
          {features.map((feature, index) => (
            <FeatureCard {...feature} key={index} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;