import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';
import { completedInterviews, prepTopics } from '../../data/interviewData';
import type { CompletedInterview, Interview, PrepTopic } from '../../types/interview';


/**
 * Represents the state structure for interviews in the Redux store.
 */
interface InterviewState {
    /** List of completed interviews with scores and feedback. */
    completedInterviews: Interview[];
    /** List of topics for practice, with completion progress. */
    prepTopics: PrepTopic[];
}

const initialState: InterviewState = {
    completedInterviews: completedInterviews as unknown as CompletedInterview[],
    prepTopics: prepTopics,
};

/**
 * Redux slice for managing interview-related data.
 * 
 * Handles saving results from AI simulation sessions, scheduling new interviews,
 * and tracking progress in practice topics.
 */
const interviewSlice = createSlice({
    name: 'interview',
    initialState,
    reducers: {
        /**
         * Saves a new interview result to the completed history.
         * Also updates the progress of relevant practice topics based on the interview focus.
         * 
         * @param {Object} report - The performance report generated by the AI.
         */
        saveInterviewResult: (state, action: PayloadAction<Record<string, unknown>>) => {
            const report = action.payload;
            const newCompletedInterview: Interview = {
                id: Date.now(),
                title: (report.position as string) || 'Interview',
                company: (report.company as string) || 'Unknown',
                position: (report.position as string) || 'Unknown',
                date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
                time: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
                duration: '30 mins',
                interviewer: 'AI Interviewer',
                status: 'completed',
                difficulty: 'Medium',
                topics: (report.topics as string[]) || [],
                score: (report.overallScore as number) || 0,
                feedback: (report.feedback as string) || '',
            };
            state.completedInterviews = [newCompletedInterview, ...state.completedInterviews];
        },

    },
});

export const { saveInterviewResult } = interviewSlice.actions;
export default interviewSlice.reducer;
