import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';
import { upcomingInterviews, completedInterviews, prepTopics } from '../../data/interviewData';

interface Interview {
    id: number;
    title: string;
    company: string;
    position: string;
    date: string;
    time: string;
    duration: string;
    interviewer: string;
    status: 'scheduled' | 'pending' | 'completed';
    difficulty: 'Easy' | 'Medium' | 'Hard';
    topics: string[];
    score?: number;
    feedback?: string;
}

interface PrepTopic {
    id: number;
    title: string;
    category: string;
    completed: number;
    total: number;
    difficulty: string;
    duration: string;
}

/**
 * Represents the state structure for interviews in the Redux store.
 */
interface InterviewState {
    /** List of upcoming, scheduled interviews. */
    upcomingInterviews: Interview[];
    /** List of completed interviews with scores and feedback. */
    completedInterviews: Interview[];
    /** List of topics for practice, with completion progress. */
    prepTopics: PrepTopic[];
}

const initialState: InterviewState = {
    upcomingInterviews: upcomingInterviews as unknown as Interview[],
    completedInterviews: completedInterviews as unknown as Interview[],
    prepTopics: prepTopics,
};

/**
 * Redux slice for managing interview-related data.
 * 
 * Handles saving results from AI simulation sessions, scheduling new interviews,
 * and tracking progress in practice topics.
 */
const interviewSlice = createSlice({
    name: 'interview',
    initialState,
    reducers: {
        /**
         * Saves a new interview result to the completed history.
         * Also updates the progress of relevant practice topics based on the interview focus.
         * 
         * @param {Object} report - The performance report generated by the AI.
         */
        saveInterviewResult: (state, action: PayloadAction<Record<string, unknown>>) => {
            const report = action.payload;
            const newCompletedInterview: Interview = {
                id: Date.now(),
                title: (report.position as string) || 'Interview',
                company: (report.company as string) || 'Unknown',
                position: (report.position as string) || 'Unknown',
                date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
                time: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
                duration: '30 mins',
                interviewer: 'AI Interviewer',
                status: 'completed',
                difficulty: 'Medium',
                topics: (report.topics as string[]) || [],
                score: (report.overallScore as number) || 0,
                feedback: (report.feedback as string) || '',
            };
            state.completedInterviews = [newCompletedInterview, ...state.completedInterviews];

            // Update prep topics progress if applicable
            const reportTopics = report.topics as string[] | undefined;
            if (Array.isArray(reportTopics)) {
                state.prepTopics = state.prepTopics.map(topic => {
                    const matchesData = reportTopics.some((t: string) =>
                        topic.title.toLowerCase().includes(t.toLowerCase()) ||
                        topic.category.toLowerCase().includes(t.toLowerCase())
                    );
                    if (matchesData && topic.completed < topic.total) {
                        return { ...topic, completed: topic.completed + 1 };
                    }
                    return topic;
                });
            }
        },
        /**
         * Adds a new interview to the upcoming schedule.
         */
        scheduleInterview: (state, action: PayloadAction<Interview>) => {
            state.upcomingInterviews = [action.payload, ...state.upcomingInterviews];
        },
        /**
         * Removes an interview from the upcoming schedule by ID.
         */
        cancelInterview: (state, action: PayloadAction<number>) => {
            state.upcomingInterviews = state.upcomingInterviews.filter(i => i.id !== action.payload);
        }
    },
});

export const { saveInterviewResult, scheduleInterview, cancelInterview } = interviewSlice.actions;
export default interviewSlice.reducer;
